#!/bin/bash

set -Eeuo pipefail
trap 'status=$?; echo "ERROR: ${BASH_SOURCE[0]}:${LINENO}: ${BASH_COMMAND} (exit ${status})" >&2' ERR

log() {
  echo "[ci_post_clone] $*"
}

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_PATH="${CI_PRIMARY_REPOSITORY_PATH:-$(cd "$SCRIPT_DIR/../.." && pwd)}"

if [[ ! -f "$REPO_PATH/pubspec.yaml" || ! -d "$REPO_PATH/ios" ]]; then
  echo "ERROR: Flutter repository root not found at: $REPO_PATH" >&2
  exit 1
fi

cd "$REPO_PATH"
log "Repository: $REPO_PATH"
log "Xcode: $(xcodebuild -version | tr '\n' ' ')"

# Pin Flutter so a future stable-channel release cannot change the cloud build.
FLUTTER_VERSION="3.41.5"
FLUTTER_DIR="$HOME/.cache/zidash/flutter-$FLUTTER_VERSION"

if [[ ! -x "$FLUTTER_DIR/bin/flutter" ]]; then
  log "Installing Flutter $FLUTTER_VERSION"
  mkdir -p "$(dirname "$FLUTTER_DIR")"
  git clone --depth 1 --branch "$FLUTTER_VERSION" \
    https://github.com/flutter/flutter.git "$FLUTTER_DIR"
fi

export PATH="$FLUTTER_DIR/bin:$PATH"
log "Flutter executable: $(command -v flutter)"
flutter --version
flutter config --no-analytics

log "Fetching Dart and Flutter plugin dependencies"
flutter pub get

log "Generating the release iOS configuration"
flutter build ios --config-only --release --no-codesign

cd "$REPO_PATH/ios"
command -v pod >/dev/null || {
  echo "ERROR: CocoaPods is not installed in this Xcode Cloud image" >&2
  exit 1
}
log "CocoaPods: $(pod --version)"

# Keep Podfile.lock authoritative. Pod installation also recreates plugin
# symlinks generated by Flutter; deleting Pods first is unnecessary.
log "Installing locked CocoaPods dependencies"
pod install --repo-update

[[ -d Runner.xcworkspace ]] || {
  echo "ERROR: ios/Runner.xcworkspace was not generated" >&2
  exit 1
}

if ! grep -q "geocoding_ios" Podfile.lock; then
  echo "ERROR: geocoding_ios is missing from ios/Podfile.lock" >&2
  exit 1
fi

if [[ ! -e .symlinks/plugins/geocoding_ios/ios/geocoding_ios.podspec ]]; then
  echo "ERROR: the geocoding_ios Flutter plugin symlink was not generated" >&2
  exit 1
fi

log "Verified geocoding_ios and Runner.xcworkspace"
log "Xcode Cloud setup completed"
